### ISSUE TITLE
フリマアプリ挙動確認

### ISSUE THREAD

**Issue by uehara0706** [uehara0706/furima_28438#9]
https://furima-28438.herokuapp.com/

BASIC_AUTH_PASSWORD:   1221
BASIC_AUTH_USER:  sim

出品者用　test1@test
                   aaaa1111

購入者用　test2@test
                   aaaa1111

4242424242424242
m5 y23
123

**Comment by oooooooba** [comment]
uehara0706さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・ユーザー管理機能の確認（必須項目を入力し、ユーザー登録ができる）
→ユーザー登録が済んでいない状態だと、トップページに飛ぶことができず、新規登録ができませんでした。

・basic認証が実装されている
→basic認証が確認できませんでした



修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by uehara0706** [comment]
修正しました。

**Comment by oooooooba** [comment]
uehara0706さん、ご提出ありがとうございます！
大変申し訳ないのですが、下記フォームから再度提出をお願い致します。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by oooooooba** [comment]
uehara0706さん、ご提出ありがとうございます！
大変申し訳ないのですが、下記のフォームより再度提出お願いします！（アプリは現在挙動確認中です）
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by oooooooba** [comment]
uehara0706さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・商品出品機能の確認
①必須項目が一つでも欠けている場合は、出品ができない
出品ができないと同時に、不足項目がある状態で出品するとエラーになってしまう
（必須項目が抜けている際に、出品ができないという動作はあっています）

②必須項目を入力した上で出品ができる
必須項目を入力して出品しようとしたところエラーになりました


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by uehara0706** [comment]
修正しました。

**Comment by rumaruma0408** [comment]
uehara0706さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◯以下のエラーが出てしまい確認を行えません。
https://i.gyazo.com/0d5de972272e4fad302687ae14f071ba.png

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by uehara0706** [comment]
修正しました。

**Comment by rumaruma0408** [comment]
uehara0706さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◯テスト用アカウントでログインができません。

◯ログアウトした状態でも、商品詳細ページを閲覧できる
→ログアウトした状態で商品詳細ページを見ることができません。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by uehara0706** [comment]
test用アカウント　修正しました。
商品を出品すればログアウト時でも出品した商品の詳細ページをみることができます。

**Comment by rumaruma0408** [comment]
uehara0706さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]

◯画像が0枚の場合は、出品できない
→出品自体はできないので大丈夫なのですが、その後以下のエラーが出てしまい確認を行えません。(トップページにも戻れませんでした。)
再度IPアドレスを開いても以下のエラーが出てしまっております。
https://i.gyazo.com/0d5de972272e4fad302687ae14f071ba.png

**修正した際は必ず、以下の最終課題完了報告フォームを再度提出お願いします！**
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by uehara0706** [comment]
修正しました。

**Comment by rumaruma0408** [comment]
uehara0706さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◯商品出品時に登録した情報が見られるようになっている
→商品の説明が表示されておりません。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by uehara0706** [comment]
修正しました。

**Comment by rumaruma0408** [comment]
uehara0706さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
